defmodule LivestokOs.AI.PromptEvolutionWorker do
  @moduledoc """
  Monthly Oban worker that reviews recent vet-consult interactions and
  proposes an improved system prompt for human review.

  ## What it does

  1. Reads the current production system prompt from
     `priv/prompts/vet_consult_system.txt`.
  2. Samples up to 20 recent confirmed cases (the `situation_summary` and
     `assistant_answer` fields) to represent real conversation quality.
  3. Sends both to the LLM asking: "How could the system prompt be improved
     based on these interactions?"
  4. Writes the proposed prompt to
     `priv/prompts/vet_consult_system_proposed_YYYY_MM.txt`
     and raises an `Alert` for developer review.

  ## Guardrails

  The worker does NOT overwrite `vet_consult_system.txt`.  A developer must
  diff and merge the proposal manually.  This preserves the deterministic
  OTP architecture: the live prompt is always a known, human-verified file.
  """

  use Oban.Worker, queue: :research, max_attempts: 2

  import Ecto.Query, warn: false

  alias LivestokOs.Repo
  alias LivestokOs.AI.ConfirmedCase
  alias LivestokOs.Operations.Alert

  require Logger

  @sample_size 20

  @impl Oban.Worker
  def perform(%Oban.Job{}) do
    current_prompt = load_current_prompt()
    samples = load_interaction_samples()

    if samples == [] do
      Logger.info("[PromptEvolution] No confirmed cases yet — skipping.")
      :ok
    else
      case generate_proposal(current_prompt, samples) do
        {:ok, proposed_prompt} ->
          path = write_proposed_prompt(proposed_prompt)
          Logger.info("[PromptEvolution] Proposed prompt written → #{path}")
          notify_reviewer(path)
          :ok

        {:error, reason} ->
          Logger.warning("[PromptEvolution] LLM call failed: #{inspect(reason)}")
          {:error, reason}
      end
    end
  end

  # ---- Private ----

  defp load_current_prompt do
    priv_dir = :code.priv_dir(:livestok_os_ai)
    path = Path.join(priv_dir, "prompts/vet_consult_system.txt")

    case File.read(path) do
      {:ok, content} -> content
      {:error, _} -> default_prompt()
    end
  end

  defp load_interaction_samples do
    Repo.all(
      from c in ConfirmedCase,
        where: not is_nil(c.confirmed_at),
        order_by: [desc: c.confirmed_at],
        limit: @sample_size,
        select: %{
          situation_summary: c.situation_summary,
          assistant_answer: c.assistant_answer
        }
    )
  end

  defp generate_proposal(current_prompt, samples) do
    sample_text =
      samples
      |> Enum.with_index(1)
      |> Enum.map(fn {s, i} ->
        """
        ### Interaction #{i}
        **Situation:** #{truncate(s.situation_summary, 400)}
        **Response:** #{truncate(s.assistant_answer, 400)}
        """
      end)
      |> Enum.join("\n")

    messages = [
      %{
        role: "system",
        content: """
        You are a prompt engineer specialising in veterinary AI assistants.
        Your task: propose an *improved* system prompt based on real interaction samples.

        Rules:
        - The prompt must keep the non-diagnosis guardrail: the AI summarises data,
          surfaces patterns, and defers clinical judgement to the veterinarian.
        - Aim for clarity, conciseness, and actionability.
        - If the current prompt is already good, say so and return it unchanged.
        - Return ONLY the proposed system prompt text — no commentary, no markdown
          code fences.  The output will be saved verbatim as the candidate prompt.
        """
      },
      %{
        role: "user",
        content: """
        ## Current system prompt

        #{current_prompt}

        ## Recent confirmed interactions (sample of #{length(samples)})

        #{sample_text}

        Based on these interactions, propose an improved system prompt.
        """
      }
    ]

    llm_client().chat_completion(messages, max_tokens: 512)
  end

  defp write_proposed_prompt(proposed_text) do
    priv_dir = :code.priv_dir(:livestok_os_ai)
    prompts_dir = Path.join(priv_dir, "prompts")
    File.mkdir_p!(prompts_dir)

    today = Date.utc_today()
    stamp = Calendar.strftime(today, "%Y_%m")
    filename = "vet_consult_system_proposed_#{stamp}.txt"
    path = Path.join(prompts_dir, filename)

    header = """
    # PROPOSED SYSTEM PROMPT — #{Calendar.strftime(today, "%B %Y")}
    # Auto-generated by PromptEvolutionWorker on #{DateTime.utc_now() |> DateTime.to_iso8601()}
    #
    # This file is a CANDIDATE only.  To apply:
    #   1. Diff against priv/prompts/vet_consult_system.txt
    #   2. Validate the non-diagnosis guardrail is preserved
    #   3. Overwrite the production file manually
    # -------------------------------------------------------------------------

    """

    File.write!(path, header <> proposed_text)
    path
  end

  defp notify_reviewer(path) do
    filename = Path.basename(path)

    first_farm_id =
      Repo.one(from f in LivestokOs.Inventory.Farm, select: f.id, limit: 1)

    if first_farm_id do
      %Alert{}
      |> Alert.changeset(%{
        farm_id: first_farm_id,
        type: "AI_PROMPT_PROPOSAL",
        message:
          "Updated system prompt candidate ready for review: #{filename}. " <>
            "See priv/prompts/ — production prompt has NOT been changed.",
        is_resolved: false,
        severity: "info",
        priority: "low"
      })
      |> Repo.insert()
    end
  end

  defp truncate(nil, _max), do: ""
  defp truncate(text, max) when byte_size(text) <= max, do: text
  defp truncate(text, max), do: String.slice(text, 0, max) <> "…"

  defp default_prompt do
    "You do not diagnose. You summarize recorded history, surface similar past patterns, " <>
      "and point to relevant research. The judgment call belongs to the veterinarian."
  end

  defp llm_client do
    Application.get_env(:livestok_os_ai, :llm_client, LivestokOs.AI.LLMClient)
  end
end
