defmodule LivestokOs.AI.ResearchIngestionWorker do
  @moduledoc """
  Oban worker that periodically ingests veterinary research articles.

  Runs in the `:research` queue, separate from consult-related processing,
  so it never blocks or slows live consult sessions.

  ## Pipeline: fetch → summarize → embed → store → markdown digest

  After each successful ingestion the worker appends a short entry to a
  monthly Markdown digest file at:

      priv/ai_research/Research_Digest_YYYY_MM.md

  This means the RAG database (pgvector) and the human-readable paper trail
  grow in sync without changing any core Elixir code.

  The fetcher is currently a stub.  Connect to an approved veterinary research
  API (e.g. PubMed E-utilities) when the API contract and access are confirmed.
  """
  use Oban.Worker,
    queue: :research,
    max_attempts: 3

  alias LivestokOs.AI.ResearchCorpus

  require Logger

  @impl Oban.Worker
  def perform(%Oban.Job{}) do
    fetcher = Application.get_env(:livestok_os_ai, :research_fetcher, __MODULE__)

    case fetcher.fetch_articles() do
      {:ok, articles} ->
        ingest_all(articles)

      {:error, reason} ->
        Logger.warning("[ResearchIngestion] Fetch failed: #{inspect(reason)}")
        {:error, reason}
    end
  end

  defp ingest_all(articles) do
    ingested =
      Enum.flat_map(articles, fn article ->
        with {:ok, summary} <- summarize(article),
             {:ok, embedding} <- embed(summary) do
          attrs = %{
            title: article.title,
            authors: article.authors,
            source: article.source,
            url: article.url,
            published_date: article.published_date,
            abstract_summary: summary,
            embedding: embedding
          }

          case ResearchCorpus.ingest_article(attrs) do
            {:ok, _} ->
              Logger.info("[ResearchIngestion] Ingested: #{article.title}")
              [Map.put(attrs, :summary, summary)]

            {:error, reason} ->
              Logger.warning("[ResearchIngestion] Failed to store: #{inspect(reason)}")
              []
          end
        else
          {:error, reason} ->
            Logger.warning(
              "[ResearchIngestion] Skipping \"#{article.title}\": #{inspect(reason)}"
            )

            []
        end
      end)

    if ingested != [] do
      write_markdown_digest(ingested)
    end

    :ok
  end

  # Appends a section for each newly ingested article to the monthly digest
  # file, creating the file (and its parent directory) if needed.
  defp write_markdown_digest(articles) do
    priv_dir = :code.priv_dir(:livestok_os_ai)
    research_dir = Path.join(priv_dir, "ai_research")
    File.mkdir_p!(research_dir)

    {year, month, _} = Date.utc_today() |> Date.to_erl()
    filename = "Research_Digest_#{year}_#{String.pad_leading("#{month}", 2, "0")}.md"
    path = Path.join(research_dir, filename)

    header =
      unless File.exists?(path) do
        "# Research Digest — #{year}/#{String.pad_leading("#{month}", 2, "0")}\n\n" <>
          "> Auto-generated by `ResearchIngestionWorker`. " <>
          "Human review recommended before relying on any claim.\n\n"
      end

    entries =
      Enum.map(articles, fn a ->
        date_str = if a.published_date, do: "#{a.published_date}", else: "unknown"
        source_str = if a.source, do: " · #{a.source}", else: ""
        url_str = if a.url, do: "\n  [Link](#{a.url})", else: ""

        """
        ## #{a.title}
        *Authors: #{a.authors || "unknown"}#{source_str} — Published: #{date_str}*

        #{a.summary}#{url_str}

        ---
        """
      end)
      |> Enum.join("\n")

    content = List.wrap(header) |> Enum.join("") |> Kernel.<>(entries)
    File.write!(path, content, [:append])
    Logger.info("[ResearchIngestion] Digest written → #{path}")
  end

  # TODO: connect to approved veterinary research API (e.g. PubMed E-utilities)
  # — do not assume API contract or access
  def fetch_articles do
    {:ok, []}
  end

  defp summarize(%{abstract: abstract}) when is_binary(abstract) do
    llm_client().chat_completion(
      [
        %{role: "system", content: "Summarize this veterinary research abstract in 2-3 sentences."},
        %{role: "user", content: abstract}
      ],
      max_tokens: 256
    )
  end

  defp summarize(_), do: {:error, :no_abstract}

  defp embed(text) do
    llm_client().embed(text)
  end

  defp llm_client do
    Application.get_env(:livestok_os_ai, :llm_client, LivestokOs.AI.LLMClient)
  end
end
